# Install dependencies
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .


ARG NEXT_PUBLIC_PROJECT_ID
ARG NEXT_PUBLIC_VIRTUALGUIGO_CONFIG_ID
ARG NEXT_PUBLIC_MIGRATIONDYNAMICS_CONFIG_ID
ARG NEXT_PUBLIC_GWR_CONFIG_ID
ARG NEXT_PUBLIC_AZURE_WILHELM_KEY
ARG NEXT_PUBLIC_GA_ID
ARG NEXT_PUBLIC_FIRESTORE_SA_KEY

ENV NEXT_PUBLIC_PROJECT_ID=$NEXT_PUBLIC_PROJECT_ID
ENV NEXT_PUBLIC_VIRTUALGUIGO_CONFIG_ID=$NEXT_PUBLIC_VIRTUALGUIGO_CONFIG_ID
ENV NEXT_PUBLIC_MIGRATIONDYNAMICS_CONFIG_ID=$NEXT_PUBLIC_MIGRATIONDYNAMICS_CONFIG_ID
ENV NEXT_PUBLIC_GWR_CONFIG_ID=$NEXT_PUBLIC_GWR_CONFIG_ID
ENV NEXT_PUBLIC_AZURE_WILHELM_KEY=$NEXT_PUBLIC_AZURE_WILHELM_KEY
ENV NEXT_PUBLIC_GA_ID=$NEXT_PUBLIC_GA_ID
ENV NEXT_PUBLIC_FIREBASE_PRIVATE_KEY=$NEXT_PUBLIC_FIREBASE_PRIVATE_KEY
ENV NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL=$NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL
ENV NEXT_PUBLIC_FIRESTORE_SA_KEY=$NEXT_PUBLIC_FIRESTORE_SA_KEY

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]

